project:
  type: website
  output-dir: docs

website:
  navbar:
    logo: logo.png
    logo-height: "35px"  # Aumente esse valor conforme necessário (ex: 45px, 50px)
    background: "#0f172a"
    tools: [] # apenas se houver
    
    left:
      - text: "Início"
        file: index.qmd

      - text: "Projeto em Andamento"
        file: projects.qmd

      - text: "Projetos de pesquisa"
        file: projeto1.qmd

      - text: "Projetos de extensão"
        file: projeto2.qmd
        
      - text: "Repositorios GitHub"
        file: repositorios.qmd
        
      - text: "Currículo"
        file: cv.qmd
        
      - text: "Contato"
        file: contact.qmd



  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Pesquisa"
        contents:
          - projects.qmd
      - section: "Ensino"
        contents:
          - materials.qmd

format:
  html:
    theme: 
      light: [lux, custom.scss]
      dark: [darkly, custom.scss]
    css: styles.css
    toc: true
    code-fold: true
    code-tools: true