---
title: "Curriculum Vitae"
format:
  html:
    css: styles.css
    toc: true
  pdf: default
---

## Informações Acadêmicas

::::: project-grid
::: project-card
## 👤 Identificação

**Nome:**\
Ítalo Gabriel da Silva

<br>

**Lattes:**\
[Currículo Lattes](https://lattes.cnpq.br/1558859767324947)

<br>

**ORCID:**\
[0009-0002-3246-446X](https://orcid.org/0009-0002-3246-446X)

<br>

**LinkedIn:**\
[Perfil LinkedIn](https://www.linkedin.com/in/%C3%ADtalo-gabriel-313194327/)

<br>

**E-mail:**\
italozil08\@gmail.com
:::

::: project-card
## 🎓 Formação Acadêmica

### Bacharelado em Estatística

**Universidade Estadual da Paraíba (UEPB)**

**Período:** 2022 – Atual

<br>

Formação voltada à inferência estatística, análise de dados, modelagem computacional, séries temporais, análise de modelos de gressão e ciência de dados.
:::
:::::

<br><br>

# Experiência em Pesquisa e Extensão

:::::: timeline
::: timeline-item
## 🌱 Projeto PIBIC — Violência Contra a Mulher na Paraíba

Projeto de pesquisa PIBIC com o tema "QUALIFICANDO E QUANTIFICANDO A VIOLÊNCIA CONTRA A MULHER NA PARAÍBA NOS ANOS DE 2021 E 2022" na cota 2023/2024, premiado com **Menção Honrosa** no evento XXXI ENIC dentro do IV Congresso UNIVERSITÁRIO DA UEPB.

Coordenação: Profª. Dra. Ivonildes da Silva Fonseca
:::

::: timeline-item
## 🛰️ Projeto PIBIC — Classificadores para Dados SAR

Projeto de pesquisa PIBIC em desenvolvimento com o tema "NOVOS CLASSIFICADORES PARA SÉRIES TEMPORAIS APLICADAS A IMAGENS SAR" na cota 2024/2025 com o professor Dr. Pedro Monteiro de Almeida Junior.

Coordenação: Prof. Dr. Pedro Monteiro de Almeida Junior.
:::

::: timeline-item
## 📊 Projeto de Extensão — Educação Financeira

Projeto de Extensão como bolsista voltado à análise e mensuração dos custos dos principais itens de consumo no município de Campina Grande–PB, no ano de 2023 com carga horária total de 90 horas. Atuação no cálculo e análise do custo da cesta básica, bem como no levantamento sistemático de preços de combustíveis, medicamentos e gás de cozinha, utilizando dados coletados localmente para avaliação do impacto no poder de compra das famílias.
:::
::::::

<br><br>

# Produção Científica

:::::: project-grid
::: project-card
## 🏆 Premiações

### Menção Honrosa — Ciências Humanas

Trabalho premiado:

**“Qualificando e quantificando a violência contra a mulher na Paraíba nos anos de 2021 e 2022”**

XXXI Encontro de Iniciação Científica — ENIC / UEPB
:::

::: project-card
## 📚 Capítulo de Livro

**Qualificando e quantificando a violência contra a mulher na Paraíba nos anos de 2021 e 2022**

In: *Rede de Saberes – Volume VII*\
Campina Grande: EDUEPB, 2025.\
p. 378–395. [DOI](https://zenodo.org/records/17372355)
:::

::: project-card
## 📝 Publicação em Anais

**Qualificando e quantificando a violência contra a mulher na Paraíba nos anos de 2021 e 2022**

XXXI Encontro de Iniciação Científica (ENIC) — UEPB, 2024.\
p. 621. [DOI](https://zenodo.org/records/16984056)
:::
::::::

<br><br>

# Participações e Apresentações em Eventos

:::::::::: timeline
::: timeline-item
## 📌 V Encontro Paraibano de Estatística — V EPBEST

Participação no congresso realizado em 2025.
:::

::: timeline-item
## 📌 IV Encontro Paraibano de Estatística — EPBEST

Participação no congresso realizado em 2023.
:::

::: timeline-item
## 🎤 Apresentação de Pôster — EPBEST 2023

Trabalho apresentado:

**“Forecasting utilizando séries temporais e machine learning (Prophet) para previsão da precipitação total mensal em Campina Grande – PB”**
:::

::: timeline-item
## 📌 Dia do Estatístico — UEPB

Participação no evento promovido pelo Departamento de Estatística da UEPB em 2023.
:::

::: timeline-item
## 📌 O Papel da Ciência de Dados na Estatística

Participação em evento acadêmico promovido pelo Departamento de Estatística da UEPB em 2023.
:::

::: timeline-item
## 📌 II Congresso Universitário da UEPB

Participação no congresso universitário realizado em 2022.
:::

::: timeline-item
## 📌 XXXI Encontro de Iniciação Científica (ENIC)

Participação no evento acadêmico XXXI ENIC em 2024.
:::
::::::::::
